apps:docs:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nDocs\\n"
apps:website:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nDocumentation\\n"
packages:actions:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nactions\\n"
packages:adb.js:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nadb.js\\n"
