apps:docs:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nDocs\\n"
apps:website:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nDocumentation\\n"
packages:test:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\ntest\\n"
