packages:
  - apps/*
  - packages/*

autoInstallPeers: false

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - unrs-resolver

peerDependencyRules:
  allowAny:
    - '*'
  ignoreMissing:
    - '*'
